export const ActionTypes = {
    SET_SELECTED_CONVERSATION: "SET_SELECTED_CONVERSATION",
    SET_MESSAGES: "SET_MESSAGES",
    SET_CONVERSATIONS: "SET_CONVERSATIONS",
    SET_DISPLAYED_CONVERSATIONS: "SET_DISPLAYED_CONVERSATIONS"
};